##\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u6b63\u5f0f\u73af\u5883\u914d\u7f6e
main.database.driverClassName=com.mysql.cj.jdbc.Driver
main.database.url=jdbc:mysql://spms.dptech.com:3306/dpspms?noAccessToProcedureBodies=true&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
main.database.username=pms
main.database.password=LfWCFkeb1

##sap\u6570\u636e\u5e93\u914d\u7f6e
sap.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
sap.database.url=jdbc:sqlserver://sap.dptech.com:1433;databaseName=DIPULive
sap.database.username=PMS
sap.database.password=8bY4JeAev

##d365\u6570\u636e\u5e93\u914d\u7f6e
d365.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
d365.database.url=jdbc:sqlserver://172.17.74.14:1433;databaseName=AXDB
d365.database.username=PMS
d365.database.password=LJZ4oPUPwn

##sms\u6570\u636e\u5e93\u914d\u7f6e
sms.database.driverClassName=com.mysql.cj.jdbc.Driver
sms.database.url=jdbc:mysql://sms.dptech.com:3306/dpsms?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
sms.database.username=pms
sms.database.password=2aH4xXd9R

##crm\u6570\u636e\u5e93\u914d\u7f6e
crm.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
crm.database.url=jdbc\:sqlserver\://172.17.74.18\:1433;databaseName\=crm_MSCRM
crm.database.username=pms
crm.database.password=JH*s54#r45F

##oa\u6570\u636e\u5e93\u914d\u7f6e
oa.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
oa.database.url=jdbc:sqlserver://172.17.74.9:1433;databaseName=v71
oa.database.username=pms
oa.database.password=Uhd87#d(dsu

##ehr\u6570\u636e\u5e93\u914d\u7f6e
ehr.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
ehr.database.url=jdbc:sqlserver://172.17.74.5:1433;databaseName=DP
ehr.database.username=pms
ehr.database.password=5RDfg*4#d)s

##sse\u6570\u636e\u5e93\u914d\u7f6e
sse.database.driverClassName=com.mysql.cj.jdbc.Driver
sse.database.url=jdbc:mysql://sse.dptech.com:3306/efrs?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
sse.database.username=pms
sse.database.password=Tgsd#23Dshd

##itr\u672c\u5730\u914d\u7f6e
itr.database.driverClassName=org.postgresql.Driver
itr.database.url=jdbc:postgresql://172.17.74.17:5432/dptech
itr.database.username=pms_reader
itr.database.password=Tv&tFL4raURMd

##license\u6570\u636e\u5e93\u914d\u7f6e
license.database.driverClassName=com.mysql.cj.jdbc.Driver
license.database.url=jdbc:mysql://172.17.90.75:3310/dplicense?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
license.database.username=pms
license.database.password=Dcfs76*hg(k

#<!-- \u521d\u59cb\u5316\u8fde\u63a5 -->  
main.database.initialSize=2
#<!-- \u6700\u5927\u7a7a\u95f2\u8fde\u63a5 -->  
main.database.maxIdle=50
#<!-- \u6700\u5c0f\u7a7a\u95f2\u8fde\u63a5 -->  
main.database.minIdle=3
#\u6700\u5927\u8fde\u63a5\u6570\u91cf  
main.database.maxActive=300
#\u662f\u5426\u5728\u81ea\u52a8\u56de\u6536\u8d85\u65f6\u8fde\u63a5\u7684\u65f6\u5019\u6253\u5370\u8fde\u63a5\u7684\u8d85\u65f6\u9519\u8bef  
main.database.logAbandoned=true
#\u662f\u5426\u81ea\u52a8\u56de\u6536\u8d85\u65f6\u8fde\u63a5  
main.database.removeAbandoned=false
#\u8d85\u65f6\u65f6\u95f4(\u4ee5\u79d2\u6570\u4e3a\u5355\u4f4d)  
main.database.removeAbandonedTimeout=1800
#<!-- \u8d85\u65f6\u7b49\u5f85\u65f6\u95f4\u4ee5\u6beb\u79d2\u4e3a\u5355\u4f4d 6000\u6beb\u79d2/1000\u7b49\u4e8e60\u79d2 -->  
main.database.maxWait=60000
#\u68c0\u67e5\u5931\u6548\u7684\u6570\u636e\u5e93\u8fde\u63a5
main.database.idleConnectionTestPeriod=10