#\u65F6\u5019\u6709\u4EE3\u7406
sys.has.proxy=false
#\u662f\u5426\u9700\u8981\u6392\u9664admin controller
sys.admin.exclude=false
#sys.admin.exclude=true
# \u6392\u9664\u7684\u8fc7\u6ee4\u6b63\u5219\u8868\u8fbe\u5f0f\uff0c\u4fdd\u7559UserController
sys.admin.exclude.filter.regex=.*.admin.*?(?<!UserController)$