sys.cas=0

#localhost
shiro.loginUrl=https://cas.dptech.com:8443/login?service=http://127.0.0.1:8083/PMS/login.html
shiro.logoutUrl=https://cas.dptech.com:8443/logout?service=http://127.0.0.1:8083/PMS/login.html
shiro.cas.serverUrlPrefix=https://cas.dptech.com:8443/
shiro.cas.service=http://127.0.0.1:8083/PMS/login.html
shiro.failureUrl=https://cas.dptech.com:8443/login?service=http://127.0.0.1:8083/PMS/login.html
shiro.successUrl=http://127.0.0.1:8083/PMS/success.html

#erh2
#shiro.loginUrl=https://cas.dptech.com:8443/login?service=http://eam.dptech.com/login.html
#shiro.logoutUrl=https://cas.dptech.com:8443/logout?service=http://eam.dptech.com/login.html
#shiro.cas.serverUrlPrefix=https://cas.dptech.com:8443/
#shiro.cas.service=http://eam.dptech.com/login.html
#shiro.failureUrl=https://cas.dptech.com:8443/login?service=http://eam.dptech.com/login.html
#shiro.successUrl=http://eam.dptech.com/success.html