sys.cas=1

#localhost
shiro.loginUrl=https://cas.dptech.com:8443/login?service=http://10.162.0.141:8083/PMS/login.html
shiro.logoutUrl=https://cas.dptech.com:8443/logout?service=http://10.162.0.141:8083/PMS/login.html
shiro.cas.serverUrlPrefix=https://cas.dptech.com:8443/
shiro.cas.service=http://10.162.0.141:8083/PMS/login.html
shiro.failureUrl=https://cas.dptech.com:8443/login?service=http://10.162.0.141:8083/PMS/login.html
shiro.successUrl=http://10.162.0.141:8083/PMS/success.html

#erh2
shiro.loginUrl=https://cas.dptech.com:8443/login?service=http://pms2.dptech.com/login.html
shiro.logoutUrl=https://cas.dptech.com:8443/logout?service=http://pms2.dptech.com/login.html
shiro.cas.serverUrlPrefix=https://cas.dptech.com:8443/
shiro.cas.service=http://pms2.dptech.com/login.html
shiro.failureUrl=https://cas.dptech.com:8443/login?service=http://pms2.dptech.com/login.html
shiro.successUrl=http://pms2.dptech.com/success.html