sys.envirment.argu=1
sys.mail.develop.receiveAddress=wenrencaike@dptech.com

sys.mail.defaultNick=\u5de5\u7a0b\u9879\u76ee\u7ba1\u7406\u7cfb\u7edf

sys.mail.server.host=mail.dptech.com
sys.mail.server.port=587
sys.mail.server.username=pms@dptech.com
sys.mail.server.password=2Bk29UamZr
sys.mail.server.fromAddress=pms@dptech.com

sys.innerMail.server.host=mail.dptech.com
sys.innerMail.server.port=587
sys.innerMail.server.username=pms@dptech.com
sys.innerMail.server.password=2Bk29UamZr
sys.innerMail.server.fromAddress=pms@dptech.com

sys.mail.develop.receiveAddress=wenrencaike@dptech.com