#\u7cfb\u7edf\u4e0a\u4f20\u6587\u4ef6\u8def\u5f84
sys.upload.path=upload/pms
plat.upload.path=upload/pms

sys.cas=1

#localhost
sys.loginUrl=https://cas.dptech.com:8443/login?service=http://10.162.0.141:8083/PMS/login.html
sys.logoutUrl=https://cas.dptech.com:8443/logout?service=http://10.162.0.141:8083/PMS/login.html
sys.cas.serverUrlPrefix=https://cas.dptech.com:8443/
sys.cas.serverLoginUrl=https://castest.dptech.com:8443/login
sys.cas.service=http://10.162.0.141:8083/PMS/login.html
sys.failureUrl=https://cas.dptech.com:8443/login?service=http://10.162.0.141:8083/PMS/login.html
sys.successUrl=http://10.162.0.141:8083/PMS/success.html