#\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u672c\u5730\u914d\u7f6e
main.database.driverClassName=com.mysql.jdbc.Driver
main.database.url=jdbc:mysql:///dpspms?noAccessToProcedureBodies=true&serverTimezone=GMT%2B8
main.database.username=root
main.database.password=!Q@W3e4r

#\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u6d4b\u8bd5\u73af\u5883\u914d\u7f6e
#main.database.driverClassName=com.mysql.jdbc.Driver
#main.database.url=jdbc:mysql://spmstest.dptech.com:3306/dppms?noAccessToProcedureBodies=true
#main.database.username=pms
#main.database.password=LfWCFkeb1
#<!-- \u521d\u59cb\u5316\u8fde\u63a5 -->  
main.database.initialSize=2
#<!-- \u6700\u5927\u7a7a\u95f2\u8fde\u63a5 -->  
main.database.maxIdle=20
#<!-- \u6700\u5c0f\u7a7a\u95f2\u8fde\u63a5 -->  
main.database.minIdle=3
#\u6700\u5927\u8fde\u63a5\u6570\u91cf  
main.database.maxActive=20
#\u662f\u5426\u5728\u81ea\u52a8\u56de\u6536\u8d85\u65f6\u8fde\u63a5\u7684\u65f6\u5019\u6253\u5370\u8fde\u63a5\u7684\u8d85\u65f6\u9519\u8bef  
main.database.logAbandoned=true
#\u662f\u5426\u81ea\u52a8\u56de\u6536\u8d85\u65f6\u8fde\u63a5  
main.database.removeAbandoned=true
#\u8d85\u65f6\u65f6\u95f4(\u4ee5\u79d2\u6570\u4e3a\u5355\u4f4d)  
main.database.removeAbandonedTimeout=180
#<!-- \u8d85\u65f6\u7b49\u5f85\u65f6\u95f4\u4ee5\u6beb\u79d2\u4e3a\u5355\u4f4d 6000\u6beb\u79d2/1000\u7b49\u4e8e60\u79d2 -->  
main.database.maxWait=60000
#\u68c0\u67e5\u5931\u6548\u7684\u6570\u636e\u5e93\u8fde\u63a5
main.database.idleConnectionTestPeriod=10
##\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u6b63\u5f0f\u73af\u5883\u914d\u7f6e
#main.database.driverClassName=com.mysql.jdbc.Driver
#main.database.url=jdbc:mysql://spms.dptech.com:3306/dpspms?noAccessToProcedureBodies=true
#main.database.username=pms
#main.database.password=LfWCFkeb1

##sap\u6570\u636e\u5e93\u914d\u7f6e
sap.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
sap.database.url=jdbc:sqlserver://sap.dptech.com:1433;databaseName=DIPULive
sap.database.username=PMS
sap.database.password=8bY4JeAev

##sms\u6570\u636e\u5e93\u914d\u7f6e
#sms.database.driverClassName=com.mysql.jdbc.Driver
#sms.database.url=jdbc:mysql://sms.dptech.com:3306/dpsms
#sms.database.username=pms
#sms.database.password=2aH4xXd9R

##sms\u672c\u5730\u914d\u7f6e
sms.database.driverClassName=com.mysql.jdbc.Driver
sms.database.url=jdbc:mysql://10.102.0.103:3307/dpsms?serverTimezone=GMT%2B8
sms.database.username=root
sms.database.password=root

##oa\u6d4b\u8bd5\u73af\u5883\u6570\u636e\u5e93\u914d\u7f6e
oa.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
oa.database.url=jdbc:sqlserver://172.153.254.211:1433;databaseName=oa8000-6
oa.database.username=pms
oa.database.password=yhzh?stW#NR

##oa\u6570\u636e\u5e93\u914d\u7f6e
#oa.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#oa.database.url=jdbc:sqlserver://172.17.74.4:1433;databaseName=oa8000-6
#oa.database.username=pms
#oa.database.password=yhzh?stW#NR

##sse\u672c\u5730\u914d\u7f6e
sse.database.driverClassName=com.mysql.jdbc.Driver
sse.database.url=jdbc:mysql://10.102.0.14:3306/efrs
sse.database.username=root
sse.database.password=r4@1K.3Hq!