jdbc.key1=Local
jdbc.key2=PMS
jdbc.key3=SMS
jdbc.key4=EHR
jdbc.key5=D365

##\u6570\u636e\u5e93\u5b57\u6bb5\u52a0\u5bc6\u5bc6\u94a5
secretkey=dp.pms

#\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u672c\u5730\u914d\u7f6e
main.database.driverClassName=com.mysql.cj.jdbc.Driver
main.database.url=jdbc:mysql:///dppms_d365?noAccessToProcedureBodies=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
main.database.username=root
main.database.password=!Q@W3e4r
#main.database.password=

jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql:///dppms_d365?noAccessToProcedureBodies=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
jdbc.username=root
#jdbc.password=r4@1K.3Hq!
jdbc.password=!Q@W3e4r
#jdbc.password=

#\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u6d4b\u8bd5\u73af\u5883\u914d\u7f6e
#main.database.driverClassName=com.mysql.cj.jdbc.Driver
#main.database.url=jdbc:mysql://spmstest.dptech.com:3306/dppms?noAccessToProcedureBodies=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
#main.database.username=pms
#main.database.password=LfWCFkeb1
#<!-- \u521d\u59cb\u5316\u8fde\u63a5 -->  
main.database.initialSize=2
#<!-- \u6700\u5927\u7a7a\u95f2\u8fde\u63a5 -->  
main.database.maxIdle=20
#<!-- \u6700\u5c0f\u7a7a\u95f2\u8fde\u63a5 -->  
main.database.minIdle=3
#\u6700\u5927\u8fde\u63a5\u6570\u91cf  
main.database.maxActive=20
#\u662f\u5426\u5728\u81ea\u52a8\u56de\u6536\u8d85\u65f6\u8fde\u63a5\u7684\u65f6\u5019\u6253\u5370\u8fde\u63a5\u7684\u8d85\u65f6\u9519\u8bef  
main.database.logAbandoned=true
#\u662f\u5426\u81ea\u52a8\u56de\u6536\u8d85\u65f6\u8fde\u63a5  
main.database.removeAbandoned=true
#\u8d85\u65f6\u65f6\u95f4(\u4ee5\u79d2\u6570\u4e3a\u5355\u4f4d)  
main.database.removeAbandonedTimeout=1800
#<!-- \u8d85\u65f6\u7b49\u5f85\u65f6\u95f4\u4ee5\u6beb\u79d2\u4e3a\u5355\u4f4d 6000\u6beb\u79d2/1000\u7b49\u4e8e60\u79d2 -->  
main.database.maxWait=60000
#\u68c0\u67e5\u5931\u6548\u7684\u6570\u636e\u5e93\u8fde\u63a5
main.database.idleConnectionTestPeriod=10
##\u7cfb\u7edf\u4e3b\u6570\u636e\u5e93\u914d\u7f6e \u6b63\u5f0f\u73af\u5883\u914d\u7f6e
#main.database.driverClassName=com.mysql.cj.jdbc.Driver
#main.database.url=jdbc:mysql://spms.dptech.com:3306/dpspms?noAccessToProcedureBodies=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
#main.database.username=pms
#main.database.password=LfWCFkeb1

##sap\u6570\u636e\u5e93\u914d\u7f6e
sap.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
sap.database.url=jdbc:sqlserver://sap.dptech.com:1433;databaseName=DIPULive
sap.database.username=PMS
sap.database.password=8bY4JeAev

##d365\u6570\u636e\u5e93\u914d\u7f6e
d365.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#d365.database.url=jdbc:sqlserver://sap.dptech.com:1433;databaseName=DIPULive
#d365.database.username=PMS
#d365.database.password=8bY4JeAev

d365.database.url=jdbc:sqlserver://172.17.90.83:1433;databaseName=AXDB
d365.database.username=SSE
d365.database.password=!q2w3e4r

d365.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
d365.database.url=jdbc:sqlserver://172.17.74.14:1433;databaseName=AXDB
d365.database.username=PMS
d365.database.password=LJZ4oPUPwn

##sms\u6570\u636e\u5e93\u914d\u7f6e
#sms.database.driverClassName=com.mysql.cj.jdbc.Driver
#sms.database.url=jdbc:mysql://sms.dptech.com:3306/dpsms?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
#sms.database.username=pms
#sms.database.password=2aH4xXd9R

##sms\u672c\u5730\u914d\u7f6e
sms.database.driverClassName=com.mysql.cj.jdbc.Driver
sms.database.url=jdbc:mysql://10.102.0.103:3307/dpsms?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
sms.database.username=root
sms.database.password=root

##oa\u6d4b\u8bd5\u73af\u5883\u6570\u636e\u5e93\u914d\u7f6e
oa.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
oa.database.url=jdbc:sqlserver://172.153.254.211:1433;databaseName=oa8000-6
oa.database.username=pms
oa.database.password=yhzh?stW#NR

##oa\u6570\u636e\u5e93\u914d\u7f6e
#oa.database.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#oa.database.url=jdbc:sqlserver://172.17.74.4:1433;databaseName=oa8000-6
#oa.database.username=pms
#oa.database.password=yhzh?stW#NR

##sse\u672c\u5730\u914d\u7f6e
sse.database.driverClassName=com.mysql.cj.jdbc.Driver
sse.database.url=jdbc:mysql://10.162.0.141:3306/dpsse?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&sendFractionalSeconds=false&useSSL=false
sse.database.username=root
sse.database.password=!Q@W3e4r

#ehr \u7cfb\u7edf\u4e3b\u6570\u636e\u6e90
ehr.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
ehr.url=jdbc:sqlserver://172.17.74.5;databaseName=DP
ehr.username=ehr4dp
ehr.password=jHt.Hy54*j2

#\u6570\u636e\u5e93\u8fde\u63a5\u6c60\u516c\u5171\u53c2\u6570
jdbc.initialSize=5
jdbc.maxActive=300
jdbc.maxIdle=50
jdbc.minIdle=5
jdbc.logAbandoned=true
jdbc.removeAbandoned=true
jdbc.removeAbandonedTimeout=1800
jdbc.maxWait=10000
jdbc.testOnBorrow=true
jdbc.validationQuery=SELECT 1
jdbc.validationQueryTimeout=2
jdbc.timeBetweenEvictionRunsMillis=300000
jdbc.minEvictableIdleTimeMillis=900000
jdbc.testWhileIdle=true
jdbc.testOnBorrowFalse=false
jdbc.numTestsPerEvictionRun=50

#\u540c\u6b65\u6570\u636e\u6e90\u8fde\u63a5\u6c60\u53c2\u6570
jdbc.initialSizeMini=1
jdbc.maxActiveMini=10
jdbc.maxIdleMini=5
jdbc.minIdleMini=1
jdbc.timeBetweenEvictionRunsMillisMini=120000
jdbc.minEvictableIdleTimeMillisMini=300000
jdbc.numTestsPerEvictionRunMini=5