jdbc.key1=Local
jdbc.key2=SMS
jdbc.key3=OFS
jdbc.key4=PMS
jdbc.key5=TMS
jdbc.key6=SAP

#mysql \u7cfb\u7edf\u4e3b\u6570\u636e\u6e90
jdbc.url=jdbc:mysql:///dposs_3?useUnicode=true&characterEncoding=UTF-8
#jdbc.url=jdbc:mysql://10.102.0.14:3306/dposs_1?useUnicode=true&characterEncoding=UTF-8
#jdbc.url=jdbc:mysql://amstest.dptech.com/dposs_1?useUnicode=true&characterEncoding=UTF-8
jdbc.driver=com.mysql.jdbc.Driver
jdbc.username=root
#jdbc.password=r4@1K.3Hq!
jdbc.password=!Q@W3e4r
#jdbc.password=root

#SMS
sms.driver=com.mysql.jdbc.Driver
sms.url=jdbc:mysql://10.102.0.14:3306/dpsms?useUnicode=true&characterEncoding=UTF-8
sms.username=root
sms.password=r4@1K.3Hq!

#SAP\u751f\u4ea7\u73af\u5883
sap.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
sap.url=jdbc:sqlserver://sap.dptech.com;databaseName=DIPULive
sap.username=oss
sap.password=jH67tfE84ih

#SAP\u6d4b\u8bd5\u73af\u5883
#sap.driver=com.mysql.jdbc.Driver
#sap.url=jdbc:mysql://10.102.0.106:3306/dp_reports?useUnicode=true&characterEncoding=UTF-8
#sap.username=root
#sap.password=!Q@W3e4r

#BMS
bms.driver=com.mysql.jdbc.Driver
bms.url=jdbc:mysql://10.102.0.14:3306/business_management?useUnicode=true&characterEncoding=UTF-8
bms.username=root
bms.password=r4@1K.3Hq!

#PMS
pms.driver=com.mysql.jdbc.Driver
pms.url=jdbc:mysql://10.102.0.106:3306/dpspms?useUnicode=true&characterEncoding=UTF-8
pms.username=root
pms.password=!Q@W3e4r

#OFS
ofs.driver=com.mysql.jdbc.Driver
ofs.url=jdbc:mysql://10.102.0.106:3306/dpofs?useUnicode=true&characterEncoding=UTF-8
ofs.username=root
ofs.password=!Q@W3e4r


#TMS
tms.driver=com.mysql.jdbc.Driver
tms.url=jdbc:mysql://10.102.0.106:3306/dptms?useUnicode=true&characterEncoding=UTF-8
tms.username=root
tms.password=!Q@W3e4r

#\u6570\u636e\u5e93\u8fde\u63a5\u6c60\u516c\u5171\u53c2\u6570
jdbc.initialSize=5
jdbc.maxActive=300
jdbc.maxIdle=50
jdbc.minIdle=5
jdbc.logAbandoned=true
jdbc.removeAbandoned=true
jdbc.removeAbandonedTimeout=180
jdbc.maxWait=10000
jdbc.testOnBorrow=true
jdbc.validationQuery=SELECT 1
jdbc.timeBetweenEvictionRunsMillis=300000
jdbc.minEvictableIdleTimeMillis=900000
jdbc.testWhileIdle=true
jdbc.testOnBorrowFalse=false
jdbc.numTestsPerEvictionRun=50

#\u540c\u6b65\u6570\u636e\u6e90\u8fde\u63a5\u6c60\u53c2\u6570
jdbc.initialSizeMini=1
jdbc.maxActiveMini=10
jdbc.maxIdleMini=5
jdbc.minIdleMini=1
jdbc.timeBetweenEvictionRunsMillisMini=120000
jdbc.minEvictableIdleTimeMillisMini=300000
jdbc.numTestsPerEvictionRunMini=10