db=mysql
jdbc.url=jdbc:mysql://10.102.0.106:3306/activiti?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
jdbc.driver=com.mysql.jdbc.Driver
jdbc.username=root
jdbc.password=!Q@W3e4r

databaseSchemaUpdate=true