# demo data properties
create.demo.users=true
create.demo.definitions=true
create.demo.models=true
create.demo.reports=true

# engine properties
engine.schema.update=true
engine.activate.jobexecutor=false
engine.asyncexecutor.enabled=true
engine.asyncexecutor.activate=true
engine.history.level=full

# email properties
#engine.email.enabled=true
#engine.email.host=localhost
#engine.email.port=1025

#\u5bfc\u51fa\u8def\u5f84
diagram.labelFontName=\u5b8b\u4f53
diagram.activityFontName=\u5b8b\u4f53
diagram.annotationFontName=\u5b8b\u4f53
export.diagram.path=/upload/diagram